### PR TITLE
new domains that point to web analytics providers

### PR DESCRIPTION
**Pull request by aliyevaa**
to discover these domains, I did the following:
1. collected DNS traffic from visiting 100k websites from the Majestic dataset
2. followed DNS resolutions for CNAME records, to identify/extract domains that point to web analytics services.
2a. added the newly identified domains to the dnscrypt-proxy.blacklist.txt (therefore, this pull request)
2b. the domains of the web analytics services were taken from dnscrypt-proxy.blacklist.txt file (March version)

Please let me know if you have any questions

### CODE REVIEW

**Comment by notracking** [comment]
Very nice list you've made there!
Why not maintain it in your own repository? I could add it from there..

```
[+] Number of whitelist matches: 2
0.0.0.0 oms.symantec.com
0.0.0.0 www.euronews.com
```

**Comment by snowdenjohnch** [comment]
Hello,

I read this beatiful artilce https://forum.xda-developers.com/android/apps-games/warden-app-manager-t4122227 on XDA.

Can you add their list, you can find it  https://send.firefox.com/download/2d10064b197b304b/#WydxB9-2SmZLtfpfT2PnBw or in the previous link, in order to protect our smartphone from trackers?

Thanks for all!

**Comment by aliyevaa** [comment]
> Very nice list you've made there!
> Why not maintain it in your own repository? I could add it from there..
> 
> ```
> [+] Number of whitelist matches: 2
> 0.0.0.0 oms.symantec.com
> 0.0.0.0 www.euronews.com
> ```

I created a repo (https://github.com/aliyevaa/cname_cloaking) with the list. 
I will be setting my system up to update the domains on the bi-weekly basis or so.
Thank you for the idea!

**Comment by llacb47** [comment]
I would not include this list. Did you just include every subdomain that CNAMEs anywhere? I can spot numerous false positives!

**Comment by aliyevaa** [comment]
ofc, no. I compared the CNAMEs to dnscrypt-proxy.blacklist.txt file that I accessed on Feb 10th, and only marked domains as trackers if they were present in the file.

**Comment by notracking** [comment]
Having a separate list helps me to do an automated audit, part of the results can be seen below. I think it's good to track how those end up there. You can have a look at our whitelist for more details on the whitelisted hosts (most have comments).

@llacb47 It would help if you would share some of those false positives.

```
[+] Total number of filters in original list: 2413
[+] Total number of dupes with notracking list (including dead lists): 71
[+] Total number of unique filters: 2342
[+] Number of whitelist matches: 2
[+] Last 50 whitelist matches:
0.0.0.0 oms.symantec.com
0.0.0.0 www.euronews.com
```

**Comment by llacb47** [comment]
@notracking @aliyevaa 

https://gist.github.com/llacb47/0eb8da1a60e0b885323cea76823e77a9

Way too many to be taken seriously.

**Comment by aliyevaa** [comment]
@notracking, thank you, will do!
@llacb47 unfortunately, trackers can be hosted on CDNs as well, just like in the case of smetrics.barclays.co.uk. So we cant just whitelist everything. 
for the true false positives, I agree, thats an ongoing work. I based off my list of the version we had on Feb 10th, but will rerun everything based on the curreent version soon

**Comment by notracking** [comment]
Please create a new issue if you would like to follow up on this.

**Pull request closed without merging**
