### PR TITLE
Update EXCLUDED.md

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Remove https://raw.githubusercontent.com/HexxiumCreations/threat-list/gh-pages/hexxiumthreatlist.txt, because it's still updating.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
BTW, it's added in 57ef7ae50b824ee86f60f0721103d6e5a092ee18 on Mar 28, 2021, it did look like not longer maintained then, but be back on Nov 28, 2021.

**Comment by notracking** [comment]
List re-added, thanks!

**Comment by PeterDaveHello** [comment]
Hi @notracking, just want to confirm so that EXCLUDEDE.md didn't need to be updated, only beed to update SOURCES.md? Thanks.

**Comment by notracking** [comment]
I need to update these kinds of things in the underlying scripts, those two files are just for public record on the states of those lists.

**Comment by PeterDaveHello** [comment]
got it, thanks!

**Pull request closed without merging**
